### ISSUE TITLE
PHP parse error on Facade.php

### ISSUE THREAD

**Issue by LifeSteala** [Fruitware/whmcs-wrapper#5]
**Describe the bug**
Installed your repository for working with WHMCS API for the first, resulted in a error with Facade.php. I called "GetClients" as a test to see if I would get a successful response.

The error received:

`[05-Aug-2020 18:27:24 Pacific/Auckland] PHP Parse error:  syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /home/hostingnz/public_html/app_emailpipe/vendor/fruitware/whmcs-wrapper/src/Facade.php on line 21`

**To Reproduce**

**Expected behavior**
A response from the API

**Additional context**
The PHP version we are using is 7.2

**Comment by keriat** [comment]
@LifeSteala hey, thanks! Will address it till Monday.

**Comment by keriat** [comment]
@LifeSteala hey, just wanted to inform you that the issue was fixed

**Comment by keriat** [comment]
Fixed 👌
